# Generated by Django 2.1.1 on 2019-03-17 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bathAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_bath', models.IntegerField(verbose_name='洗浴人数')),
                ('num_brand', models.IntegerField(default='', verbose_name='洗浴手牌号')),
                ('num_back', models.IntegerField(verbose_name='搓背人数')),
                ('remark_bath', models.CharField(default='', max_length=225, verbose_name='备注（洗浴）')),
                ('day_bath', models.CharField(default='', max_length=32, verbose_name='洗浴时间')),
                ('price_bath', models.IntegerField(verbose_name='洗浴价格')),
            ],
            options={
                'verbose_name_plural': '2.洗浴',
            },
        ),
        migrations.CreateModel(
            name='cataHouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('house_name', models.CharField(default='', max_length=20, verbose_name='住房类型')),
            ],
            options={
                'verbose_name_plural': '3.房间类型',
            },
        ),
        migrations.CreateModel(
            name='electricityAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_elect', models.CharField(default='', max_length=60, verbose_name='缴费时间')),
                ('num_elect', models.CharField(default='', max_length=60, verbose_name='用电度数')),
                ('price_elect', models.IntegerField(null=True, verbose_name='电费')),
            ],
            options={
                'verbose_name_plural': '8.电费',
            },
        ),
        migrations.CreateModel(
            name='expenseAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expen_cate', models.CharField(default='', max_length=20, verbose_name='支出类型')),
                ('price_account', models.IntegerField(verbose_name='支出金额')),
                ('day_expense', models.CharField(default='', max_length=20, verbose_name='时间')),
                ('remark_account', models.CharField(default='', max_length=225, verbose_name='支出（备注）')),
            ],
            options={
                'verbose_name_plural': '4.支出',
            },
        ),
        migrations.CreateModel(
            name='houseAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20, verbose_name='房客姓名')),
                ('sex', models.CharField(default='', max_length=20, verbose_name='房客性别')),
                ('identity', models.CharField(default='', max_length=20, verbose_name='房客身份证')),
                ('num_house', models.IntegerField(verbose_name='房间号')),
                ('day_house', models.IntegerField(verbose_name='订房天数')),
                ('price_house', models.IntegerField(verbose_name='房价')),
                ('day_time', models.CharField(default='', max_length=20, verbose_name='住房时间')),
                ('remark_house', models.CharField(default='', max_length=225, verbose_name='备注（住房）')),
                ('cata_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qqsys.cataHouse', verbose_name='住房类型')),
            ],
            options={
                'verbose_name_plural': '1.住房',
            },
        ),
        migrations.CreateModel(
            name='incomeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_income', models.CharField(default='', max_length=32, verbose_name='住房类型')),
                ('total_bath', models.IntegerField(null=True, verbose_name='洗浴总收入')),
                ('total_House', models.IntegerField(null=True, verbose_name='住房总收入')),
                ('total_store', models.IntegerField(null=True, verbose_name='百货总收入')),
                ('total_bath_house', models.IntegerField(null=True, verbose_name='住房和洗浴总收入')),
                ('total_pay', models.IntegerField(null=True, verbose_name='总支出')),
                ('total_income', models.IntegerField(null=True, verbose_name='总收入')),
                ('remark_income', models.CharField(default='', max_length=225, verbose_name='备注（收入）')),
            ],
            options={
                'verbose_name_plural': '5.总收入',
            },
        ),
        migrations.CreateModel(
            name='otherAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cata_other', models.CharField(default='', max_length=32, verbose_name='其他收入类型')),
                ('price_other', models.IntegerField(null=True, verbose_name='住房其他收入价格')),
                ('day_other', models.CharField(default='', max_length=32, verbose_name='时间')),
                ('remark_other', models.CharField(default='', max_length=225, verbose_name='备注（其他）')),
            ],
            options={
                'verbose_name_plural': '7.其他收入',
            },
        ),
        migrations.CreateModel(
            name='storeAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cata_store', models.CharField(default='', max_length=32, verbose_name='百货类型')),
                ('price_store', models.IntegerField(null=True, verbose_name='百货价格')),
                ('day_store', models.CharField(default='', max_length=32, verbose_name='时间')),
                ('remark_store', models.CharField(default='', max_length=225, verbose_name='备注（百货）')),
            ],
            options={
                'verbose_name_plural': '6.百货收入',
            },
        ),
    ]
