# Generated by Django 2.1.1 on 2019-03-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qqsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=20, verbose_name='密码')),
                ('avatar', models.FileField(default='avatars/default.png', upload_to='avatars/', verbose_name='头像')),
                ('email', models.CharField(max_length=32, null=True, verbose_name='邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
