# Generated by Django 2.1.1 on 2019-03-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qqsys', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '9.用户信息'},
        ),
    ]
